apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: be-server
  namespace: default
spec:
  endpoints:
    - interval: 10s
      port: metrics-port
      scrapeTimeout: 9s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/part-of: be-service