apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.server.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.server.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.name }}
    spec:
      containers:
        - name: {{ .Values.server.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: VITE_API_BASE_URL
              value: {{ .Values.server.baseApi }}
