# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: public.ecr.aws/v2h8l1j0/nc-learners-frontend
  tag: "1.1.0"

# Frontend server variables
server:
  name: fe-server
  baseApi: ad422aa3fd4e643b4af04018dd421b7e-6446255.eu-west-2.elb.amazonaws.com

# Frontend service variables
service:
  name: fe-service
  type: LoadBalancer
  port: 80
